
POST https://gaader-heroku.herokuapp.com/auth/admin/login
Content-Type: application/json

{
    "email": "karl@gmail.com",
    "password": "seme"
}

###
GET https://gaader-heroku.herokuapp.com/auth/admin/logout

###
GET https://gaader-heroku.herokuapp.com/auth/admin/loggedin