GET https://gaader-heroku.herokuapp.com/admin/bruger/tester

###


GET https://gaader-heroku.herokuapp.com/admin/bruger

###

GET https://gaader-heroku.herokuapp.com/admin/bruger/5ee3542d7a8e4141841cf97a
###
POST https://gaader-heroku.herokuapp.com/admin/bruger
Content-Type: application/json

{
    "brugernavn": "karli",
    "email": "karli@gmail.com",
    "password": "seme"
}

###
DELETE https://gaader-heroku.herokuapp.com/admin/bruger/5ee3542d7a8e4141841cf97a
###
PATCH https://gaader-heroku.herokuapp.com/admin/bruger/5ee3542d7a8e4141841cf97a
Content-Type: application/json

{
    "brugernavn": "Kim"
}

