GET https://gaader-heroku.herokuapp.com/gaader/tester

###


GET https://gaader-heroku.herokuapp.com/gaader

###

GET https://gaader-heroku.herokuapp.com/gaader/5ee72d486ddb2c0017959737

###
POST https://gaader-heroku.herokuapp.com/gaader/admin
Content-Type: application/json

{
    "gaadeTekst": "surt",
    "gaadeSvar": "citroner og mere"
}

###
DELETE https://gaader-heroku.herokuapp.com/gaader/admin/5ee72d486ddb2c0017959737
###
PATCH https://gaader-heroku.herokuapp.com/gaader/admin/5ee72d486ddb2c0017959737
Content-Type: application/json

{
    "gaadeTekst": "New overskrift"
}
